name: aguhon-dev

volumes:
  mongodb:

services:
  aguhon-database:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
      - ./database/mongoinit.js:/docker-entrypoint-initdb.d/mongoinit.js:ro
    command: --port 27018
    ports:
      - ${DATABASE_PORT}:27018
    env_file: 
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  app:
    build: .
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    env_file:
      - ./.env
    environment:
      ON_DOCKER: "true"
    depends_on:
        aguhon-database:
          condition: service_started
