name: aguhon

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
      - ./database/mongoinit.js:/docker-entrypoint-initdb.d/mongoinit.js:ro
    ports:
      - "27017:27017"

volumes:
  mongodb:
