name: aguhon

volumes:
  mongodb:

# networks: 
#   backend:

services:
  database:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - ./database/mongoinit.js:/docker-entrypoint-initdb.d/mongoinit.js:ro
    ports:
      - 27017:27017
    restart: always
    # networks:
    #   - backend
  app:
      build: .
      ports:
        - 5173:3000
      volumes: 
        - ./:/usr/src/app
        - /app/node_modules
      depends_on:
        - database
      # networks:
      #   - backend
      links:
        - database
      # external_links:
      #   - database
