name: aguhon-prod

volumes:
  mongodb:

services:
  database:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
      - ./database/mongoinit.js:/docker-entrypoint-initdb.d/mongoinit.js:ro
    ports:
      - ${DATABASE_PORT}:27017
    env_file: 
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  app:
    image: kaiserace/aguhon-app:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    environment:
      ON_DOCKER: "true"
    depends_on:
        database:
          condition: service_started

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_LABEL_ENABLE: 1
      WATCHTOWER_SCHEDULE: '* * * * *'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

